using System.Globalization;
using System.IO;
using System.Text;

namespace Sky1stCharacterStudio;

public enum UiLanguage
{
    Chinese,
    English
}

/// <summary>
/// Runtime UI language and the small set of game-specific translations that
/// cannot come from the installed game's localized name table.
/// </summary>
public static class UiText
{
    private static readonly Dictionary<string, (string Chinese, string English)> Texts =
        new(StringComparer.Ordinal)
        {
            ["window.title"] = ("空之轨迹 the 1st · 角色模型工作台", "Trails in the Sky the 1st · Character Model Studio"),
            ["app.heading"] = ("游击士协会 · 角色模型工作台", "Bracer Guild · Character Model Studio"),
            ["app.subtitle"] = ("选择游戏目录，调整模型，一键导出并安装。安装会备份旧文件，原始 PAC 保持只读。", "Choose the game folder, adjust a model, then export and install it. Existing files are backed up; original PAC archives stay read-only."),
            ["offline"] = ("离线模式", "Offline mode"),
            ["scan.panel"] = ("资源扫描", "Resource scan"),
            ["game.folder"] = ("游戏目录（扫描与安装目标）", "Game folder (scan and install target)"),
            ["browse"] = ("浏览…", "Browse…"),
            ["models"] = ("角色模型", "Character models"),
            ["not.scanned"] = ("未扫描", "Not scanned"),
            ["filter.tooltip"] = ("输入 chr 编号或角色名进行筛选", "Filter by chr ID or character name"),
            ["selected.model"] = ("当前模型", "Selected model"),
            ["waiting.scan"] = ("等待扫描", "Waiting for scan"),
            ["scan.button"] = ("扫描游戏资源", "Scan game resources"),
            ["live.heading"] = ("实时模型 · 拖动旋转，滚轮缩放", "Live model · drag to rotate, scroll to zoom"),
            ["portrait.status"] = ("头像/贴图预览会从 image.pac 读取；雪拉扎德可切换原版与调整后 3D 渲染", "Portrait and texture previews are read from image.pac; Scherazard can switch between original and adjusted 3D renders."),
            ["toggle.original"] = ("切换原版", "Show original"),
            ["toggle.adjusted"] = ("返回当前调整", "Show adjusted"),
            ["full.body"] = ("全身", "Full body"),
            ["upper.body"] = ("上半身", "Upper body"),
            ["contour.heading"] = ("形体轮廓预览", "Shape contour preview"),
            ["contour.label"] = ("轮廓预览", "Contour preview"),
            ["contour.note"] = ("滑条只改变导出模型的参数强度；最终网格由已验证的模型后端生成。", "The slider changes the exported model strength; the final mesh is generated by the verified model backend."),
            ["adjustment.mode"] = ("调整方式", "Adjustment"),
            ["mode.width"] = ("整体宽度", "Overall width"),
            ["mode.chest"] = ("胸部／胸廓（自动定位）", "Chest / torso (automatic placement)"),
            ["strength.help"] = ("0 = 原版；整体宽度：−500 为 75%，1000 为 150%；胸部在 ±100% 外采用平滑响应并自动保护轮廓", "0 = original; overall width: −500 = 75%, 1000 = 150%; chest adjustments beyond ±100% use a smooth response and protect the silhouette automatically"),
            ["reset"] = ("还原原模型", "Restore original"),
            ["reset.tooltip"] = ("将强度归零，回到原模型位置", "Set strength to zero and return to the original model"),
            ["install"] = ("保存并应用到游戏", "Save & apply to game"),
            ["install.tooltip"] = ("生成当前强度的模型，备份现有文件并安装到所选游戏目录。请先退出游戏。", "Generate the selected shape, back up existing files, and install it in the selected game folder. Exit the game first."),
            ["summon"] = ("启用 F8 测试召唤", "Enable F8 test summon"),
            ["restore"] = ("撤销上次安装", "Undo last installation"),
            ["status.ready"] = ("准备扫描。调整完成后，退出游戏并点击“保存并应用到游戏”。", "Ready to scan. After adjusting a model, exit the game and click “Save & apply to game”."),
            ["status.choose.folder"] = ("请先选择游戏目录。", "Choose the game folder first."),
            ["status.read.index"] = ("正在读取 FPAC 索引（只读，不会抽取整个大包）…", "Reading the FPAC index (read-only; the full archive will not be extracted)…"),
            ["status.scan.complete"] = ("扫描完成：{0} 个基础角色模型，{1} 个找到头像贴图。原始 PAC 保持只读。", "Scan complete: {0} base character models, {1} portrait textures found. Original PAC archives remain read-only."),
            ["status.scan.failed"] = ("扫描失败：{0}。请确认目录下存在 pac\\steam\\asset_common_model.pac。", "Scan failed: {0}. Make sure pac\\steam\\asset_common_model.pac exists in the selected folder."),
            ["status.language.changed"] = ("界面语言已切换为中文。", "Interface language changed to English."),
            ["status.loading.model"] = ("正在自动提取 {0} 的模型和贴图…", "Automatically extracting the model and textures for {0}…"),
            ["status.preview.failed"] = ("无法加载此调整方式：{0}", "Unable to load this adjustment: {0}"),
            ["status.preview.adjusted"] = ("实时预览：{0}% · 导出使用同一强度。{1}；光照以游戏内为准。", "Live preview: {0}% · exports use the same strength. {1}; lighting is determined by the game."),
            ["status.preview.original"] = ("正在对照原版（0%）；返回当前调整可查看 {0}%。", "Comparing with the original (0%); choose “Show adjusted” to view {0}% again."),
            ["status.installing"] = ("正在生成 {0}% 模型并安装到：{1}", "Generating the {0}% model and installing it to: {1}"),
            ["status.exporting.only"] = ("正在生成 {0}% 模型；本次无法安装：{1}", "Generating the {0}% model; installation is unavailable: {1}"),
            ["status.exported.only"] = ("模型已生成：{0}\n未写入游戏目录：{1}", "Model generated: {0}\nNothing was installed to the game: {1}"),
            ["status.installed.summon"] = ("已安装 {0}% 模型到：{1}\nF8 召唤本次角色；F9 切换版本后再按 F8 刷新。备份：{2}", "Installed the {0}% model to: {1}\nF8 summons this character; press F9 to switch versions, then F8 to refresh. Backup: {2}"),
            ["status.installed.summon.skipped"] = ("已安装 {0}% 模型到：{1}\nF8 测试召唤无法启用，已自动关闭；角色正常出场时仍会使用修改模型。原因：{3}\n备份：{2}", "Installed the {0}% model to: {1}\nF8 test summon could not be enabled and was turned off; the edited model still applies when the character appears normally. Reason: {3}\nBackup: {2}"),
            ["status.installed.normal"] = ("已安装 {0}% 模型到：{1}\n角色正常出场时生效；测试召唤已关闭。备份：{2}", "Installed the {0}% model to: {1}\nThe change applies when the character appears normally; test summon is disabled. Backup: {2}"),
            ["status.restored"] = ("已撤销上次安装：{0}", "Undid the last installation: {0}"),
            ["choose.game.title"] = ("选择游戏目录（包含 sora_1st.exe 的文件夹）", "Choose the game folder (the folder containing sora_1st.exe)"),
            ["mode.detecting"] = ("正在检测骨骼；成年资格单独检查", "Detecting bones; adult eligibility is checked separately"),
            ["model.size"] = ("模型大小：{0}", "Model size: {0}"),
            ["model.info"] = ("模型信息：{0}", "Model info: {0}"),
            ["found"] = ("已找到", "Found"),
            ["not.found"] = ("未找到", "Not found"),
            ["portrait"] = ("头像：{0}", "Portrait: {0}"),
            ["portrait.found"] = ("已找到角色头像贴图", "Character portrait texture found"),
            ["portrait.missing"] = ("未找到角色头像，使用轮廓预览", "No character portrait found; using contour preview"),
            ["support"] = ("自动读取模型、材质和骨骼；加载成功后可调整", "Models, materials and bones are read automatically; adjust after loading succeeds"),
            ["bone.detect"] = ("骨骼检测：{0}", "Bone detection: {0}"),
            ["eligibility"] = ("资格：{0}", "Eligibility: {0}"),
            ["bone.names.separator"] = ("、", ", "),
            ["missing.textures"] = ("缺少 {0} 张贴图，对应区域显示灰色。", "{0} texture(s) missing; affected areas are shown in gray."),
            ["shape.limited"] = ("已按模型约束局部位移，降低极限强度翻面的风险。", "Local displacement was limited for this model to reduce the risk of inverted faces at extreme strengths."),
            ["bone.chest"] = ("胸部／胸廓自动定位", "chest / torso automatic placement"),
            ["bone.width"] = ("整体宽度", "overall width"),
            ["not.available"] = ("不可用", "Unavailable"),
            ["disabled.reason"] = ("该模型不满足成年资格或缺少可用胸部骨骼", "This model is not eligible as an adult or has no usable chest bones"),
            ["zero"] = ("原版", "original"),
            ["model.contour"] = ("{0} 轮廓", "{0} contour"),
            ["scherazard.contour"] = ("雪拉扎德轮廓", "Scherazard contour"),
            ["preview.adjusted.info"] = ("实时预览：{0}% · 导出使用同一强度。{1}；光照以游戏内为准。", "Live preview: {0}% · exports use the same strength. {1}; lighting is determined by the game."),
            ["preview.original.info"] = ("正在对照原版（0%）；返回当前调整可查看 {0}%。", "Comparing with the original (0%); choose “Show adjusted” to view {0}% again."),
            ["age.unknown"] = ("年龄资料不足", "Age information unavailable"),
            ["age.adult"] = ("已确认成年", "Confirmed adult"),
            ["age.adult.default"] = ("原生未登记角色 · 默认成年", "Base-game character not listed · adult by default"),
            ["age.minor"] = ("已确认未成年", "Confirmed minor"),
            ["age.years"] = ("{0} 岁", "age {0}"),
            ["age.basis.default"] = ("尚无可核对的本作年龄资料", "No verifiable age information is available for this game"),
            ["age.basis.archive"] = ("由游戏原始模型归档扫描发现；年龄目录未将其标记为未成年", "Found in the original game model archive; the age catalog does not mark it as a minor"),
            ["age.basis.official"] = ("《空之轨迹 the 1st》角色介绍公布年龄", "Published character age for Trails in the Sky the 1st"),
            ["age.basis.table"] = ("本作资源表明确标注：", "Identified by the game's resource table: "),
            ["age.basis.name.table"] = ("本作名称表标注为", "The game's name table identifies this as "),
            ["age.source.archive"] = ("游戏原始 asset_common_model.pac", "Original game asset_common_model.pac"),
            ["error.game.running"] = ("游戏正在运行，请先退出游戏再安装。", "The game is running. Exit it before installing."),
            ["error.invalid.game.root"] = ("请选择同时包含 sora_1st.exe 和 pac 文件夹的游戏根目录。", "Choose the game root containing both sora_1st.exe and the pac folder."),
            ["error.path.outside"] = ("安装路径超出目标目录。", "The installation path is outside the target directory."),
            ["error.link.path"] = ("安装目标或来源包含链接目录，请选择实际目录：{0}", "The installation source or target contains a linked directory; choose the real directory: {0}"),
            ["error.same.directory"] = ("文件目标被同名目录占用：{0}", "A directory already occupies the target file path: {0}"),
            ["error.install.interrupted"] = ("检测到游戏启动，停止安装并还原。", "The game started during installation; installation was stopped and rolled back."),
            ["error.install.verify"] = ("安装校验失败：{0}", "Installation verification failed: {0}"),
            ["error.install.rollback.incomplete"] = ("安装失败，部分文件还原失败。备份：{0}", "Installation failed and some files could not be rolled back. Backup: {0}"),
            ["error.install.rollback"] = ("安装失败，已还原本次修改。备份：{0}", "Installation failed; this change was rolled back. Backup: {0}"),
            ["error.package.incomplete"] = ("测试包不完整：{0}", "The test package is incomplete: {0}"),
            ["error.restore.changed"] = ("安装后文件已被其他程序修改，为避免覆盖，停止恢复：{0}", "A file changed after installation; restore stopped to avoid overwriting it: {0}"),
            ["error.restore.interrupted"] = ("游戏启动，停止恢复。", "The game started during restore; restore was stopped."),
            ["error.restore.none.for.game"] = ("没有此游戏目录尚未撤销的安装记录。", "There is no un-restored installation record for this game folder."),
            ["error.not.ready"] = ("请等待所选模型加载成功。", "Wait for the selected model to finish loading."),
            ["error.generation"] = ("模型生成失败，未安装。", "Model generation failed; nothing was installed."),
            ["error.restore.running"] = ("请先退出游戏再恢复。", "Exit the game before restoring."),
            ["error.no.backup"] = ("没有可恢复的安装备份。", "There is no installation backup to restore."),
            ["error.unsupported.version"] = ("当前游戏程序版本 {0} 不在已验证版本中。此测试版仅支持云豹 Steam 1.0.5.0／1.0.7.0 的指定文件，未安装任何内容。", "Game executable version {0} is not verified. This beta supports only the specified CLE Steam 1.0.5.0/1.0.7.0 files; nothing was installed."),
            ["error.compatibility.missing"] = ("缺少游戏兼容性清单 supported-game.json，安装已停止。请重新解压完整工具包。", "The game compatibility manifest supported-game.json is missing. Installation stopped; extract the full tool archive again."),
            ["export.helper.width"] = ("自动模型调整：整体宽度；按当前模型解析骨骼和顶点偏移。", "Automatic model adjustment: overall width; bone and vertex offsets are resolved from the selected model."),
            ["export.helper.chest"] = ("自动模型调整：胸部／胸廓；按当前模型解析骨骼和顶点偏移。", "Automatic model adjustment: chest / torso; bone and vertex offsets are resolved from the selected model."),
            ["export.notes.verified"] = ("已从校验过的原版生成指定强度。", "Generated at the requested strength from a verified original model."),
            ["export.notes.unverified"] = ("该角色尚未完成拓扑验证，本次只导出原版模型副本和参数预设。", "This character has not completed topology validation; only an original model copy and parameter preset were exported."),
            ["export.message"] = ("已导出 {0} 的 {1}% 形体模型。", "Exported the {1}% shape model for {0}."),
            ["export.copy.message"] = ("已导出模型副本；形体补丁未应用", "Exported a model copy; the shape patch was not applied"),
            ["export.unverified.message"] = ("已导出 {0} 的原版副本，形体参数已写入预设（尚未验证该模型的拓扑）。", "Exported the original copy of {0}; shape parameters were written to a preset (this model's topology is not yet validated)."),
            ["runtime.override"] = ("模型：{0} ({1})\r\n形体强度：{2}%\r\n\r\n这是离线生成的测试包副本。请先退出游戏，再手工将此目录内容复制到游戏目录；工具不会自动安装或启动游戏。\r\n", "Model: {0} ({1})\r\nShape strength: {2}%\r\n\r\nThis is an offline-generated test package. Exit the game first, then copy this folder into the game directory manually; the tool will not install or launch the game automatically.\r\n"),
            ["error.no.runtime"] = ("找不到已验证的游戏运行组件", "The verified game runtime components could not be found"),
            ["error.no.model"] = ("找不到自动模型处理程序", "The automatic model processor could not be found"),
            ["error.processor.start"] = ("模型处理程序启动失败", "The model processor could not start"),
            ["error.pac.missing"] = ("找不到 PAC 文件", "PAC file not found"),
            ["error.pac.missing.path"] = ("找不到 PAC 文件：{0}", "PAC file not found: {0}"),
            ["error.pac.format"] = ("只支持 FPAC 资源包", "Only FPAC archives are supported"),
            ["error.no.mesh"] = ("模型没有可显示的网格", "The model has no displayable meshes"),
            ["error.archive.parent"] = ("输出路径无父目录", "The output path has no parent directory"),
            ["error.preview.script"] = ("找不到 DDS 预览脚本", "The DDS preview script could not be found"),
            ["error.preview.start"] = ("无法启动 DDS 预览脚本", "The DDS preview script could not start"),
            ["error.age.catalog"] = ("年龄资料版本不一致，请重新启动工作台", "The age data version is inconsistent; restart the studio."),
            ["error.summon.invalid.id"] = ("角色模型编号格式错误", "The character model ID has an invalid format"),
            ["error.summon.script.function"] = ("找不到召唤脚本所需的游戏函数", "The game function required by the summon script was not found"),
            ["error.summon.script.missing"] = ("F8 测试召唤需要游戏文件：{0}。本次将关闭召唤，继续安装模型。", "F8 test summon requires this game file: {0}. The summon will be disabled and model installation will continue."),
            ["error.summon.script.function.path"] = ("F8 测试召唤所需的脚本条目不在：{0}。本次将关闭召唤，继续安装模型。", "The F8 summon script entry is missing from: {0}. The summon will be disabled and model installation will continue."),
            ["error.summon.target"] = ("召唤目标模型未安装到测试包", "The summon target model is missing from the test package"),
            ["error.summon.builder"] = ("缺少召唤脚本生成器", "The summon-script builder is missing"),
            ["error.summon.builder.start"] = ("召唤脚本生成器启动失败", "The summon-script builder could not start"),
            ["error.summon.build.failed"] = ("召唤脚本生成失败：{0}", "The summon script could not be generated: {0}"),
            ["error.summon.config"] = ("召唤配置缺少 {0}", "The summon configuration is missing {0}"),
            ["error.pac.small"] = ("PAC 文件过小", "The PAC file is too small"),
            ["error.pac.entries"] = ("PAC 条目数异常", "The PAC entry count is invalid"),
            ["error.pac.range"] = ("PAC 条目表超出文件范围", "The PAC entry table is outside the file bounds"),
            ["error.pac.offset"] = ("PAC 条目偏移无效", "A PAC entry has an invalid offset"),
            ["error.pac.preview.large"] = ("预览条目过大", "The preview entry is too large"),
            ["error.pac.name.truncated"] = ("PAC 文件名被截断", "A PAC filename is truncated"),
            ["error.pac.name.long"] = ("PAC 文件名过长", "A PAC filename is too long"),
            ["error.pac.data.truncated"] = ("PAC 条目数据被截断", "PAC entry data is truncated"),
            ["error.pac.file.truncated"] = ("PAC 文件被截断", "The PAC file is truncated"),
            ["error.names.format"] = ("角色名称表格式不支持", "The character-name table format is unsupported"),
            ["error.names.bounds"] = ("名称表头越界", "The character-name table header is outside the file bounds"),
            ["error.names.offset"] = ("名称表字符串越界", "A character-name string offset is outside the file bounds"),
            ["error.names.terminated"] = ("名称表字符串未结束", "A character-name string is not terminated"),
            ["error.names.layout"] = ("名称表行布局不支持", "The character-name table row layout is unsupported"),
            ["placeholder.no.portrait"] = ("暂无头像预览", "No portrait preview"),
            ["comparison.title"] = ("原版 / 调整后 3D 对照", "Original / adjusted 3D comparison"),
            ["comparison.original"] = ("原版", "Original"),
            ["comparison.adjusted"] = ("调整后（100%）", "Adjusted (100%)"),
            ["comparison.crop.original"] = ("胸部局部放大 · 原版", "Chest close-up · original"),
            ["comparison.crop.adjusted"] = ("胸部局部放大 · 调整后", "Chest close-up · adjusted"),
            ["comparison.note"] = ("右侧是调整后模型；下方局部图用于观察细微轮廓差异。", "The adjusted model is on the right; the close-ups below show small contour differences."),
            ["contour.strength"] = ("{0}  ·  形体强度 {1}%", "{0}  ·  shape strength {1}%"),
            ["contour.local.note"] = ("胸廓与相邻衣料的局部轮廓示意", "Local contour guide for the torso and adjacent clothing")
        };

    private static readonly Dictionary<string, string> EnglishCharacterNames =
        new(StringComparer.OrdinalIgnoreCase)
        {
            ["chr0001"] = "Joshua", ["chr0003"] = "Olivier", ["chr0005"] = "Agate", ["chr0007"] = "Zin",
            ["chr0100"] = "Kurtz", ["chr0103"] = "Kulatz", ["chr0108"] = "Colonel Richard", ["chr0109"] = "Cassius",
            ["chr0110"] = "Philip", ["chr0113"] = "General Morgan", ["chr0116"] = "Major Cid", ["chr0117"] = "Professor Alba",
            ["chr0118"] = "Loewe", ["chr0301"] = "Duke Dunan", ["chr0307"] = "Nial", ["chr0313"] = "Gilbert",
            ["chr0315"] = "Gustav", ["chr0316"] = "Dr. Russell", ["chr0319"] = "Old Man Lugran", ["chr0320"] = "Jean",
            ["chr0321"] = "Ain", ["chr0331"] = "Principal Collins", ["chr5000"] = "Estelle", ["chr5002"] = "Scherazard",
            ["chr5004"] = "Kloe", ["chr5006"] = "Tita", ["chr5101"] = "Anelace", ["chr5102"] = "Caluna",
            ["chr5106"] = "Josette", ["chr5107"] = "Lieutenant Julia", ["chr5111"] = "Kirika", ["chr5114"] = "Captain Kanone",
            ["chr5300"] = "Queen Alicia", ["chr5308"] = "Dorothy", ["chr5310"] = "Mayor Mabel", ["chr5311"] = "Lila",
            ["chr5318"] = "Aina"
        };

    private static UiLanguage _current = UiLanguage.Chinese;
    private static bool _initialized;
    private static string? _preferencePath;

    public static UiLanguage Current => _current;
    public static bool IsEnglish => _current == UiLanguage.English;
    public static event EventHandler? LanguageChanged;

    public static void Initialize()
    {
        if (_initialized) return;
        _initialized = true;
        _preferencePath = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "Sky1stCharacterStudio", "language.txt");
        try
        {
            if (File.Exists(_preferencePath))
            {
                var value = File.ReadAllText(_preferencePath, Encoding.UTF8).Trim();
                _current = value.Equals("en", StringComparison.OrdinalIgnoreCase)
                    ? UiLanguage.English : UiLanguage.Chinese;
            }
        }
        catch
        {
            _current = UiLanguage.Chinese;
        }
    }

    public static void SetLanguage(UiLanguage language, bool persist = true)
    {
        Initialize();
        if (_current == language) return;
        _current = language;
        if (persist && _preferencePath is not null)
        {
            try
            {
                Directory.CreateDirectory(Path.GetDirectoryName(_preferencePath)!);
                File.WriteAllText(_preferencePath, language == UiLanguage.English ? "en\n" : "zh\n", Encoding.UTF8);
            }
            catch
            {
                // A read-only profile should not prevent the editor from running.
            }
        }
        LanguageChanged?.Invoke(null, EventArgs.Empty);
    }

    public static string T(string key)
    {
        if (!Texts.TryGetValue(key, out var text)) return key;
        return IsEnglish ? text.English : text.Chinese;
    }

    public static string F(string key, params object?[] args)
    {
        return string.Format(CultureInfo.InvariantCulture, T(key), args);
    }

    public static string CharacterName(string modelId, string sourceName)
    {
        if (!IsEnglish) return sourceName;
        if (EnglishCharacterNames.TryGetValue(modelId, out var known)) return known;
        if (string.IsNullOrWhiteSpace(sourceName)) return $"Character {modelId}";
        if (sourceName.StartsWith("角色 ", StringComparison.Ordinal)
            || sourceName.StartsWith("未登记名称", StringComparison.Ordinal)
            || sourceName.Any(character => character is >= '\u3400' and <= '\u9fff'))
            return $"Character {modelId}";
        return TranslateGenericName(sourceName, modelId);
    }

    private static string TranslateGenericName(string sourceName, string modelId)
    {
        var name = sourceName.Replace("（", " (").Replace("）", ")");
        name = name.Replace("中年男性学者", "Middle-aged Scholar", StringComparison.Ordinal)
            .Replace("中年男子", "Middle-aged Man", StringComparison.Ordinal)
            .Replace("老年男性", "Elderly Man", StringComparison.Ordinal)
            .Replace("老年男子", "Elderly Man", StringComparison.Ordinal)
            .Replace("中年女子", "Middle-aged Woman", StringComparison.Ordinal)
            .Replace("老年女子", "Elderly Woman", StringComparison.Ordinal)
            .Replace("幼儿", "Toddler", StringComparison.Ordinal)
            .Replace("少女", "Young Girl", StringComparison.Ordinal)
            .Replace("女孩", "Girl", StringComparison.Ordinal)
            .Replace("工房工匠", "Workshop Craftsman", StringComparison.Ordinal)
            .Replace("厨师", "Cook", StringComparison.Ordinal)
            .Replace("飞行船船长", "Airship Captain", StringComparison.Ordinal)
            .Replace("神父", "Priest", StringComparison.Ordinal)
            .Replace("管家", "Butler", StringComparison.Ordinal)
            .Replace("王国军军官", "Royal Army Officer", StringComparison.Ordinal)
            .Replace("测试君", "Test", StringComparison.Ordinal)
            .Replace("孩童", "Child", StringComparison.Ordinal)
            .Replace("草席卷", "Special outfit", StringComparison.Ordinal);
        return name == sourceName ? $"{sourceName} ({modelId})" : name;
    }

    public static string AgeDisplay(CharacterAgeInfo info)
    {
        var key = info.Status switch
        {
            "adult" when info.IsAdult && info.DefaultedFromBaseGame => "age.adult.default",
            "adult" when info.IsAdult => "age.adult",
            "minor" => "age.minor",
            _ => "age.unknown"
        };
        return info.Age.HasValue ? $"{T(key)} · {F("age.years", info.Age.Value)}" : T(key);
    }

    public static string AgeBasis(string basis, string source)
    {
        if (!IsEnglish) return basis;
        if (basis.StartsWith("由游戏原始模型归档扫描发现", StringComparison.Ordinal)) return T("age.basis.archive");
        if (basis.StartsWith("《空之轨迹", StringComparison.Ordinal)) return T("age.basis.official");
        if (basis.StartsWith("本作资源表明确标注：", StringComparison.Ordinal)) return T("age.basis.table") + basis["本作资源表明确标注：".Length..];
        if (basis.StartsWith("本作名称表标注为", StringComparison.Ordinal)) return T("age.basis.name.table") + basis["本作名称表标注为".Length..];
        return T("age.basis.default");
    }

    public static string AgeSource(string source)
    {
        if (!IsEnglish) return source;
        return source.StartsWith("游戏原始 asset_common_model.pac", StringComparison.Ordinal)
            ? T("age.source.archive") : source;
    }

    public static string BoneDetail(string detail)
    {
        if (!IsEnglish || string.IsNullOrWhiteSpace(detail)) return detail;
        if (detail.StartsWith("已根据脊柱、颈部和蒙皮权重自动定位胸廓表面", StringComparison.Ordinal))
            return "Estimated the torso surface from spine, neck and skinning weights" + (detail.Contains("（估计）", StringComparison.Ordinal) ? " (estimated)" : "");
        if (detail.StartsWith("已识别左右根部；缺失末端由对侧对称推定", StringComparison.Ordinal))
            return "Left and right roots recognized; missing tips inferred symmetrically from the opposite side and nearby mesh checked";
        if (detail.StartsWith("已识别左右根部和末端骨骼", StringComparison.Ordinal))
            return "Left and right root and tip bones recognized";
        if (detail.StartsWith("已识别左右胸部骨骼；缺少完整末端", StringComparison.Ordinal))
            return "Left and right chest bones recognized, but complete tips are missing; this structure is unsupported";
        if (detail.StartsWith("同名骨骼的坐标不一致", StringComparison.Ordinal))
            return "Bones with the same name have inconsistent coordinates";
        if (detail.StartsWith("未发现胸部骨骼标记", StringComparison.Ordinal))
            return "No chest-bone markers found";
        if (detail.StartsWith("检测到候选骨骼，但无法唯一匹配", StringComparison.Ordinal))
            return "Candidate bones found, but root and tip pairs could not be matched uniquely";
        if (detail.StartsWith("骨骼坐标无效或根部与末端重合", StringComparison.Ordinal))
            return "Bone coordinates are invalid or the root and tip overlap";
        return detail;
    }
}
